# Generated by Django 5.2.7 on 2025-10-24 18:59

import django.db.models.deletion
import simple_history.models
import smart_selects.db_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('organization_structure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='department',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='project', chained_model_field='project', null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization_structure.department'),
        ),
        migrations.AddField(
            model_name='account',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization_structure.project'),
        ),
        migrations.AddField(
            model_name='account',
            name='team',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='department', chained_model_field='department', null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization_structure.team'),
        ),
        migrations.CreateModel(
            name='HistoricalAccount',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(db_index=True, max_length=50)),
                ('role', models.CharField(choices=[('Associate', 'Associate'), ('Lead', 'Lead'), ('Manager', 'Manager')], max_length=50)),
                ('email', models.EmailField(db_index=True, max_length=100)),
                ('emp_id', models.PositiveIntegerField(db_index=True)),
                ('date_joined', models.DateTimeField(blank=True, editable=False)),
                ('last_login', models.DateTimeField(blank=True, editable=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superadmin', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('department', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='project', chained_model_field='project', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organization_structure.department')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organization_structure.project')),
                ('team', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='department', chained_model_field='department', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organization_structure.team')),
            ],
            options={
                'verbose_name': 'historical account',
                'verbose_name_plural': 'historical accounts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
