# Generated by Django 5.2.7 on 2025-10-25 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_department_account_project_account_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='location',
            field=models.CharField(choices=[('Pune', 'Pune'), ('Nagpur', 'Nagpur'), ('Ahmedabad', 'Ahmedabad')], default='Pune', max_length=50),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='location',
            field=models.CharField(choices=[('Pune', 'Pune'), ('Nagpur', 'Nagpur'), ('Ahmedabad', 'Ahmedabad')], default='Pune', max_length=50),
        ),
    ]
