# Generated by Django 5.2.7 on 2025-10-28 19:31

import django.db.models.deletion
import smart_selects.db_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0002_alter_historicalsubtask_subtask_expected_efforts_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltask',
            name='assigned_to',
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='subtask',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='task_category', chained_model_field='task_category', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='task_management.subtask'),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='task_category',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='team', chained_model_field='team', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='task_management.taskcategory'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.AlterField(
            model_name='task',
            name='subtask',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='task_category', chained_model_field='task_category', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task_management.subtask'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_category',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='team', chained_model_field='team', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task_management.taskcategory'),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, null=True, related_name='received_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
